Separate occcupancy grid
Imperial-Driverless/lightweight_lidar_only_simulator pull request #25
Opened 2022-02-27 12:29 UTC by qme1519

Simulator can now take an argument to specify a file for the occupancy grid as an image. This image can be modified to add any obstacles that are needed. Solves #24

2022-02-27 14:31 UTC, mateusz-lichota requested changes

2022-02-27 14:31 UTC, mateusz-lichota commented on launch/simulate_with_twist_interface.launch.py
>          origin:  [{orig_x}, {orig_y}, 0.]
I think this method is a bit messy. First, passing just a png without metadata could cause weird scaling bugs, so we should instead pass the .yaml metadata file (for example, map.yaml). Second, if we have passed the yaml metadata we should ignore the 'track_file' argument, and not raise an exception if it is not present. 

Since we would be passing a .yaml file now, the `occupancy_grid_file` argument name should be changed to  `occupancy_grid_yaml` to reflect this. Additionally, we would no longer have to even read the file, as we would be able to just pass it to the `map_server_node`'s  `yaml_filename` parameter.

In case `occupancy_grid_yaml` is not passed we should stick to the current behavior.

2022-02-27 14:32 UTC, mateusz-lichota commented on launch/simulate_with_twist_interface.launch.py
>          origin:  [{orig_x}, {orig_y}, 0.]
+ map.png should be renamed to something like 'small_track_with_obstacles.png' and get an associated .yaml file (just a copy of map.yaml generated for the standard small_track map)

2022-02-27 18:33 UTC, qme1519 commented on launch/simulate_with_twist_interface.launch.py
>          origin:  [{orig_x}, {orig_y}, 0.]
The launcher now takes the yaml file of the modified image, which references the modified image and can directly be used in the map server. Behaviour modified such that providing the yaml file does not trigger the previous behaviour for track files. Exception only raised when no occupancy grid and no track file is provided.

2022-02-28 10:25 UTC, mateusz-lichota approved these changes

2022-02-28 10:25 UTC, merged